server:
  port: 8030

spring:
  application:
    name: sl-admin
  data:
    redis:
      host: ${XSL_REDIS_HOST:localhost}
      port: ${XSL_REDIS_PORT:6380}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
